name: Mekom Solutions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ESM_NAME: "@sidvaish97/esm-patient-medical-supply-orders-app"
  JS_NAME: "openmrs-esm-patient-medical-supply-orders-app.js"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_API: 'http://127.0.0.1:9080'
      TURBO_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
      TURBO_TEAM: ${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Setup local cache server for Turborepo
        uses: felixmosh/turborepo-gh-artifacts@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

      - name: Run verification
        run: yarn verify

      - name: Build package
        run: yarn turbo build --color --concurrency=5

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist
          if-no-files-found: warn
          compression-level: 6
          overwrite: true
